### ISSUE TITLE
Make a Chinese Version?

### ISSUE THREAD

**Issue by MEMZ-Edge01** [cw2k/Adobe-GenP#2]

**Comment by cw2k** [comment]
Hmm maybe you, dear reader of this reply, can do.
Just open the source in ya editor and translate the "Strings".
If that git pull request is to hard to do create a gist and post the link here.
Or use pastebin.com or just post ya source here as reply.
I may handle to get them both side by didethis.

However I m not fee6l good in doing some Google translate English to Chinese port since I've no clue about the Chinese language.

I may only do translation of languages belonging to the Indo-European family.

**Comment by AdrianRonaldo10** [comment]
Hey, I've done the translation and made a pull request, check when you are free~ :)

**Comment by Murzik77** [comment]
https://github.com/cw2k/Adobe-GenP/assets/79037853/49359042-cea5-468b-a457-7768f2643723
