### ISSUE TITLE
macOS?

### ISSUE THREAD

**Issue by alexunderboots** [cw2k/Adobe-GenP#9]
will there be mac os support?

**Comment by cw2k** [comment]
I guess not.
I don't have a mac. 

I just use an iphone6 for about a year.
and did a jail break (chessra1n and later altstore an unc0ver)
Ran some ssh and an game emulator to 
 on it an did some exploration of the apple ecosystem.
Manage to ran some pirated ipa on it through the panda store. All the forbidden Apple is afraid of.

My hackentosh project a year ago failed.

Well since Apple ditched the powerpc CPU the
mac uses same instructionset and CPU than Windows so there's a small chance the patch pattern may also work for mac.

However when it comes to wrap the binary object code thing get different. I don't know if in case you change some binary on ios you need to also change it's checksum or signature to be able to execute it.

So if someone likes to try it out gets it work and makes a pull request i ll accept it. However I ve no plans to touch the apple stuff myself.
